[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/",
]

# Testing
fuzz_runs = 256
verbosity = 2

# RPC URLs
[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC}"
localhost = "http://localhost:8545"

# Etherscan
[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# Formatting
[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
